version: '3.8'

services:
  redis:
    image: redis:latest

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  migrate:
    build: .
    command: poetry run python manage.py migrate
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      migrate:
        condition: service_completed_successfully



  celery_worker:
    build: .
    command: poetry run celery -A CVProject worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started

volumes:
  postgres_data: