version: '3.8'

services:
  redis:
    image: redis:latest

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    build: .
    command: poetry run gunicorn CVProject.wsgi:application --bind 0.0.0.0:8000 --workers 1
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - certbot_etc:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web


  celery_worker:
    build: .
    command: poetry run celery -A CVProject worker -l info
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
  static_volume:
  certbot_etc:
  certbot_webroot:

