LANGUAGES = [
    ("Cornish", "Cornish"),
    ("Manx", "Manx"),
    ("Breton", "Breton"),
    ("Inuktitut", "Inuktitut"),
    ("Kalaallisut", "Kalaallisut"),
    ("Romani", "Romani"),
    ("Occitan", "Occitan"),
    ("Ladino", "Ladino"),
    ("Northern Sami", "Northern Sami"),
    ("Upper Sorbian", "Upper Sorbian"),
    ("Kashubian", "Kashubian"),
    ("Zazaki", "Zazaki"),
    ("Chuvash", "Chuvash"),
    ("Livonian", "Livonian"),
    ("Tsakonian", "Tsakonian"),
    ("Saramaccan", "Saramaccan"),
    ("Bislama", "Bislama"),
]